<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>disable</Nullable>
    <Authors>JBOBYH</Authors>
    <Copyright>Copyright (c) JBOBYH 2026</Copyright>
    <AssemblyVersion>1.2.0</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <Version>$(AssemblyVersion)</Version>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <SPTPath>..\..</SPTPath>
    <OutPath>$(SPTPath)\BepInEx\plugins\JBOBYH</OutPath>
    <AssemblySearchPaths>
      $(AssemblySearchPaths);
      $(SPTPath)\EscapeFromTarkov_Data\Managed;
      $(SPTPath)\BepInEx\core;
      $(SPTPath)\BepInEx\plugins;
      $(SPTPath)\BepInEx\plugins\spt;
      $(SPTPath)\BepInEx\plugins\sinai-dev-UnityExplorer;
    </AssemblySearchPaths>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp" />
    <Reference Include="0Harmony" />
    <Reference Include="spt-common" />
    <Reference Include="spt-reflection" />
    <Reference Include="BepInEx" />
    <Reference Include="Comfort" />
    <Reference Include="Comfort.Unity" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="Sirenix.Serialization" />
    <Reference Include="Tyfon.UIFixes" />
    <Reference Include="Unity.TextMeshPro" />
    <Reference Include="UnityEngine" />
    <Reference Include="UnityEngine.AssetBundleModule" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="UnityEngine.ImageConversionModule" />
    <Reference Include="UnityEngine.IMGUIModule" />
    <Reference Include="UnityEngine.InputLegacyModule" />
    <Reference Include="UnityEngine.TextRenderingModule" />
    <Reference Include="UnityEngine.UI" />
    <Reference Include="UnityExplorer.BIE5.Mono" />
  </ItemGroup>

  <Target Name="CopyToBepInEx" AfterTargets="Build">
    <MakeDir Directories="$(OutPath)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(OutPath)" />
  </Target>

</Project>
